In [7]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('datasets/lab6.txt', sep = '\t', header=None)
df.columns = ['X_1', 'X_2', 'Y']
df.head()

X_1    X_2  Y
0  0.85  17.45  2
1  0.75  15.60  2
2  3.30  15.45  2
3  5.25  14.20  2
4  4.90  15.65  2

In [11]:
n_samples = df.shape[0]
n_features = df.shape[1] - 1
n_samples, n_features

(373, 2)

In [27]:
# making the feature vector
X = np.zeros((n_samples, n_features))
for i in range(n_samples):
    X[i] = df['X_1'][i], df['X_2'][i]
X, X.shape

(array([[ 0.85, 17.45],
        [ 0.75, 15.6 ],
        [ 3.3 , 15.45],
        [ 5.25, 14.2 ],
        [ 4.9 , 15.65],
        [ 5.35, 15.85],
        [ 5.1 , 17.9 ],
        [ 4.6 , 18.25],
        [ 4.05, 18.75],
        [ 3.4 , 19.7 ],
        [ 2.9 , 21.15],
        [ 3.1 , 21.85],
        [ 3.9 , 21.85],
        [ 4.4 , 20.05],
        [ 7.2 , 14.5 ],
        [ 7.65, 16.5 ],
        [ 7.1 , 18.65],
        [ 7.05, 19.9 ],
        [ 5.85, 20.55],
        [ 5.5 , 21.8 ],
        [ 6.55, 21.8 ],
        [ 6.05, 22.3 ],
        [ 5.2 , 23.4 ],
        [ 4.55, 23.9 ],
        [ 5.1 , 24.4 ],
        [ 8.1 , 26.35],
        [10.15, 27.7 ],
        [ 9.75, 25.5 ],
        [ 9.2 , 21.1 ],
        [11.2 , 22.8 ],
        [12.6 , 23.1 ],
        [13.25, 23.5 ],
        [11.65, 26.85],
        [12.45, 27.55],
        [13.3 , 27.85],
        [13.7 , 27.75],
        [14.15, 26.9 ],
        [14.05, 26.55],
        [15.15, 24.2 ],
        [15.2 , 24.75],
        [12.2 , 20.9 ],
        [12.15, 

In [28]:
# making the adjacency matrix W
sigma = 0.5
W = np.zeros((n_samples, n_samples))
for i in range(n_samples):
    sum = 0
    for j in range(n_samples):
        if (i != j):
            W[i][j] = np.exp(-(np.sum((X[i] - X[j])**2)) / sigma)
        else :
            W[i][j] = 0
W

array([[0.00000000e+00, 1.04368245e-03, 2.05087358e-09, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.04368245e-03, 0.00000000e+00, 2.15009184e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.05087358e-09, 2.15009184e-06, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 3.19047620e-02, 3.60656314e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.19047620e-02, 0.00000000e+00, 7.11770323e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.60656314e-03, 7.11770323e-01, 0.00000000e+00]])

In [30]:
# making the degree matrix
D = np.zeros((n_samples, n_samples))
for i in range(n_samples):
    sum = 0
    for j in range(n_samples):
        sum += W[i][j]
    D[i][i] = sum
D

array([[1.04368464e-03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.04583254e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.70308276e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        7.45746974e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.26217041e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.81387925e+00]])

In [35]:
# laplacian Matrix L
L = D - W
# eigen value decomposition of L
eigenvalues, eigenvectors = np.linalg.eig(L)
# we need to sort both eigenvalues and eigenvectors otherwise their pair mismatches
idx = np.argsort(eigenvalues)[::-1] # in descending order
eig_vals = eigenvalues[idx]
eig_vecs = eigenvectors[:, idx]