<a href="https://colab.research.google.com/github/mohIITech/learning_machine_learning/blob/colab/colab_notebooks/exercise_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Import torch

In [1]:
import torch

# 2. Create a random tensor of shape(7, 7)

In [2]:
random_tensor = torch.rand(size=[7, 7])

# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
random_tensor_2 = torch.rand(size=[1, 7])
random_tensor_2_t  = torch.transpose(random_tensor_2, 0, 1)

In [4]:
random_tensor_2, random_tensor_2_t

(tensor([[0.4843, 0.7562, 0.9145, 0.3871, 0.9953, 0.0684, 0.2743]]),
 tensor([[0.4843],
         [0.7562],
         [0.9145],
         [0.3871],
         [0.9953],
         [0.0684],
         [0.2743]]))

In [5]:
product = torch.mm(random_tensor, random_tensor_2_t)
product

tensor([[1.7457],
        [1.5446],
        [2.7354],
        [1.8841],
        [1.8771],
        [2.5962],
        [1.5983]])

# 4. Set the random seed to 0 and do 2 & 3 over again.

In [6]:
RANDOM_SEED = 0
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_3 = torch.rand(size=[7, 7])
random_tensor_4 = torch.rand(size=[1, 7])

print(f"Before : \n tensor_3{random_tensor_3} \n tensor_4{random_tensor_4}")

random_tensor_4 = torch.transpose(random_tensor_4, 0, 1)

print(f"After : \n tensor_3{random_tensor_3} \n tensor_4{random_tensor_4}")

product_2 = torch.matmul(random_tensor_3, random_tensor_4)
product_2

Before : 
 tensor_3tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) 
 tensor_4tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
After : 
 tensor_3tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [7]:
torch.cuda.is_available()

True

In [13]:
torch.cuda.get_device_name()

'Tesla T4'

# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [11]:
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(seed=RANDOM_SEED_GPU)

random_tensor_5 = torch.rand(size=[7, 7], device='cuda')
random_tensor_6 = torch.rand(size=[1, 7], device='cuda')

random_tensor_5, random_tensor_6

(tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
         [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
         [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
         [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
         [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
         [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
         [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
        device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255, 0.1114, 0.6812, 0.3608, 0.1715]],
        device='cuda:0'))

# 7. Perform a matrix multiplication on the tensors you created in 6

In [14]:
product_3 = torch.matmul(random_tensor_5, torch.transpose(random_tensor_6, 0, 1))
product_3

tensor([[0.9558],
        [1.2227],
        [0.9335],
        [1.6030],
        [0.9344],
        [0.5282],
        [0.5664]], device='cuda:0')

# 8. Find the maximum and minimum values of the output of 7.

In [16]:
torch.max(product_3), torch.min(product_3)

(tensor(1.6030, device='cuda:0'), tensor(0.5282, device='cuda:0'))

# 9. Find the maximum and minimum index values of the output of 7.

In [18]:
torch.argmax(product_3), torch.argmin(product_3)

(tensor(3, device='cuda:0'), tensor(5, device='cuda:0'))

# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [21]:
# random seed
RANDOM_SEED =7
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_7 = torch.rand(size=[1, 1, 1, 10], device='cuda')
random_tensor_7

tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0')

In [29]:
# removing the 1 dimensions
new_tensor = torch.squeeze(random_tensor_7)
new_tensor, new_tensor.ndim, new_tensor.shape
## this changes the original tensor also

(tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 1,
 torch.Size([10]))